name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Download source code
        uses: actions/checkout@v2
      - name: Lint
        run: "apk add -qU luacheck && luacheck ."
      - name: Check for spaces in indentation
        run: "grep -nE '^[[:blank:]]? [[:blank:]]?' *.lua && exit 1 || true"
